[package]
name = "puppy-bowl"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"
rand = "0.8"
wasm-logger = "0.2"
yew = "0.19"
gloo-timers = "0.2"
pathfinding = "3.0.6"

[build-dependencies]
image = "0.23.14"
rand = "0.8"
